---
- name: install Docker for 5G Node
  hosts: my_5g_nodes
  become: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: install Docker.io
      apt:
        name: docker.io
        state: present

    - name: ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
